# -*- coding: utf-8 -*-
"""Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lqroNnvUwfK5GTOjFQ8NksX0EtjBngXo
"""

"""
Load Python variables from Javascript

Variables to load:
customer_budget
customer_home_preference
point_list

"""


import pandas as pd
import numpy as np
df= pd.read_csv("https://drive.google.com/file/d/1eLKnzztyAiEWcOstiuib_2Kvy1ErzYBZ/view?usp=sharing")

df.rename(columns={'green_space': 'Number of Green Spaces', 'travel_bank': 'Travel Time to Bank Station', 'safety': 'Safety','school_density':'Number of Schools', 
                   'pub_number':'Number of Pubs', 'well_being_score':'Well Being Score','restaurant_number':'Number of Restaurants'}, inplace=True)

# customer_home_preference = int(input("Please enter how many bedrooms you need:"))

customer_budget = js_budget
customer_home_preference = js_bedrooms
point_list = js_pointlist

if customer_home_preference == 1:
  df2=df.drop(["rent_per_month_2bed"], axis = 1)
  df2=df2.drop(["rent_per_month_3bed"], axis = 1)
  df2=df2.drop(["rent_per_month_4bed"], axis = 1)
elif customer_home_preference == 2:
  df2=df.drop(["rent_per_month_1bed"], axis = 1)
  df2=df2.drop(["rent_per_month_3bed"], axis = 1)
  df2=df2.drop(["rent_per_month_4bed"], axis = 1)
elif customer_home_preference == 3:
  df2=df.drop(["rent_per_month_1bed"], axis = 1)
  df2=df2.drop(["rent_per_month_2bed"], axis = 1)
  df2=df2.drop(["rent_per_month_4bed"], axis = 1)
elif customer_home_preference == 4:
  df2=df.drop(["rent_per_month_1bed"], axis = 1)
  df2=df2.drop(["rent_per_month_2bed"], axis = 1)
  df2=df2.drop(["rent_per_month_3bed"], axis = 1)

#customer_budget = int(input("Please enter your budget:"))

if customer_home_preference == 1:
  filtered_customer_list = df2.loc[(df2['rent_per_month_1bed'] <= customer_budget)]

elif customer_home_preference == 2:
  filtered_customer_list = df2.loc[(df2['rent_per_month_2bed'] <= customer_budget)]

elif customer_home_preference == 3:
  filtered_customer_list = df2.loc[(df2['rent_per_month_3bed'] <= customer_budget)]

elif customer_home_preference == 4:
  filtered_customer_list = df2.loc[(df2['rent_per_month_4bed'] <= customer_budget)]

columns = df2.columns
columns = list(columns)
columns.remove('Borough')
if customer_home_preference == 1:
  columns.remove('rent_per_month_1bed')

elif customer_home_preference == 2:
  columns.remove('rent_per_month_2bed')

elif customer_home_preference == 3:
  columns.remove('rent_per_month_3bed')

elif customer_home_preference == 4:
  columns.remove('rent_per_month_4bed')

point_list = []
'''print('Rate between 1 and 5 how important each of the following variables are for your accomodation (1 = not important and 5 = being essential')
for i in range (len(columns)):
  added_word = columns[i]
  added_word = str(added_word)
  customer_ranking = input("Please enter your point for " + added_word + ": ")
  point_list.append(customer_ranking)'''

new_matrix = filtered_customer_list[['Number of Green Spaces','Travel Time to Bank Station','Safety','Number of Schools','Number of Pubs','Well Being Score','Number of Restaurants']]
new_matrix.to_numpy()

vector = np.array(point_list,dtype=float)
matrix = np.array(new_matrix,dtype=float)
matrix_transpose = matrix.T
final_mark = np.dot(vector,matrix_transpose)
final_mark = final_mark.T
final_mark=list(final_mark)
x = filtered_customer_list.iloc[:, 0]
x = pd.DataFrame([x]).T
x['Points'] = final_mark
x_final = x.sort_values(by=['Points'], inplace=False, ascending=False)
final_list = x_final.head(3)
final_list = final_list.iloc[:,0:1]
final_list = final_list.values.tolist()

empty_list = []
for i in range(0,3):
  for j in range(0,1):
    final_result = final_list[i][j]
    empty_list.append(final_result)

print("Top 3 boroughs to live according to your choices :")

for i in range(0,3):
  print(empty_list[i])

